import { NOW, recordFixture, newOrderFixture } from '../../exchange-core/test/fixtures/domain.js';
import { capabilities } from '../../exchange-core/test/fixtures/adapter.js';
import { adapterProfile, getBinanceProfile } from '../../exchange-binance/src/profiles.js';
const profile = adapterProfile(getBinanceProfile('binance-spot-testnet-v1'));
export function fixture() {
  const record = recordFixture();
  const binding = {
    tenantId: '11111111-1111-4111-8111-111111111111',
    accountId: '22222222-2222-4222-8222-222222222222',
    mode: 'TESTNET',
    profile,
  };
  const limits = {
    valuationAsset: 'USDT',
    maxOrderNotional: '100',
    maxInstrumentExposure: '200',
    maxAssetExposure: '300',
    maxAccountExposure: '400',
    maxUserExposure: '500',
    maxConcurrentPositions: 3,
    maxOpenOrders: 5,
    maxLeverage: '5',
    maxDailyRealizedLoss: '20',
    maxDailyTotalLoss: '30',
    maxDrawdownRate: '0.2',
    maxOrdersPerMinute: 10,
    minAvailableBalance: '1',
    maxPriceDeviationRate: '0.1',
    maxSpreadRate: '0.02',
    minLiquidityNotional: '50',
    maxEvidenceAgeMs: 5000,
  };
  return {
    now: NOW,
    binding,
    adapterVersion: 'v1',
    platform: { ...limits },
    user: { ...limits },
    order: newOrderFixture(record),
    record,
    capabilities: capabilities
      .filter((x) => ['LIMIT_ORDER', 'MARKET_ORDER', 'REDUCE_ONLY'].includes(x.feature))
      .map((x) => ({ ...x, profile, checkedAt: NOW - 1000, expiresAt: NOW + 60000 })),
    snapshot: {
      binding: structuredClone(binding),
      instrumentId: record.instrument.id,
      revision: '9007199254740993',
      sourceId: 'certified-fixture',
      sourceAt: NOW - 100,
      reconciledAt: NOW - 50,
      complete: true,
      unknownExposure: false,
      valuationAsset: 'USDT',
      instrumentExposure: '10',
      assetExposure: '20',
      accountExposure: '30',
      userExposure: '40',
      positionQuantity: '0',
      positionEvidence: {
        mode: 'SPOT',
        accountMode: profile.accountMode,
        accountId: binding.accountId,
        instrumentId: record.instrument.id,
        sourceId: 'certified-fixture',
        revision: '9007199254740993',
        asOf: NOW - 100,
        side: 'NET',
        quantity: '0',
      },
      committedReductionQuantity: '0',
      instrumentHasPendingEntry: false,
      concurrentPositions: 1,
      openOrders: 1,
      ordersInLastMinute: 1,
      leverage: '1',
      availableAsset: 'USDT',
      availableAmount: '1000',
      dailyNetRealizedPnl: '0',
      adjustedOpeningEquity: '100',
      adjustedCurrentEquity: '100',
      adjustedPeakEquity: '100',
      utcDayStart: Math.floor(NOW / 86400000) * 86400000,
      lossBaselineComplete: true,
      pauses: { global: false, user: false, connection: false, strategy: false },
      circuit: 'CLOSED',
      health: {
        database: 'HEALTHY',
        limiter: 'HEALTHY',
        authentication: 'HEALTHY',
        exchangeRest: 'HEALTHY',
        privateStream: 'HEALTHY',
        clock: 'HEALTHY',
        latency: 'HEALTHY',
        rejectRate: 'HEALTHY',
        maintenance: 'HEALTHY',
      },
      market: {
        sourceId: 'book-and-price-fixture',
        asOf: NOW - 20,
        complete: true,
        referencePrice: '10',
        lowerExecutionPrice: '9.9',
        upperExecutionPrice: '10.1',
        bid: '9.95',
        ask: '10.05',
        liquidityNotional: '1000',
        liquidityAsset: 'USDT',
        priceAsset: 'USDT',
        fxFromAsset: 'USDT',
        fxToAsset: 'USDT',
        fxKind: 'IDENTITY',
        quoteToValuation: '1',
        fxSourceId: 'identity-fx',
        fxAsOf: NOW - 20,
        kind: 'LAST',
        executionBoundEnforced: true,
        feeAsset: 'USDT',
        maxFeeRate: '0.01',
      },
    },
  };
}
